# Dockerfile.tester
FROM debian:12

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y curl openssh-client netcat-openbsd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]